### PR TITLE
bitset: add from with length func

### PR DESCRIPTION
**Pull request by paralin**
Allowing to reconstruct a bitset from the outputs of Len() and Bytes().

### CODE REVIEW

**Comment by lemire** [comment]
I do not understand the need for this function?

**Comment by paralin** [comment]
I want to store the BitSet as `[]uint64` (output of Bytes) and Length so that I can reconstruct an identical BitSet later

Not seeing a way to do that with existing APIs, the From will construct one with length == uint(len(buf))*64 which is different from the original Length.

**Comment by lemire** [comment]
Why won't `From(set)` do?

**Comment by paralin** [comment]
From will construct one with length == uint(len(buf))*64 which is different from the original Length.

**Comment by lemire** [comment]
Running tests.

**Pull request merged**
